### ISSUE TITLE
wasm range request fails on Firefox

### ISSUE THREAD

**Issue by Fil** [duckdb/duckdb-wasm#1932]
### What happens?

If you type this query into shell.duckdb.org:
`SELECT bbox FROM read_json('https://earthquake.usgs.gov/earthquakes/feed/v1.0/summary/all_day.geojson');`

on Firefox, you get a "failed range request" error.

See https://github.com/observablehq/framework/issues/1886

### To Reproduce

Open Firefox to shell.duckdb.org, and type this query:
`SELECT bbox FROM read_json('https://earthquake.usgs.gov/earthquakes/feed/v1.0/summary/all_day.geojson');`

### Browser/Environment:

Firefox 133.0.3 (aarch64)

### Device:

Macbook Air

### DuckDB-Wasm Version:

@duckdb/duckdb-wasm@1.29.1-dev18.0

### DuckDB-Wasm Deployment:

https://shell.duckdb.org/

### Full Name:

Fil Rivière

### Affiliation:

Observable

**Comment by fkauker-fsq** [comment]
I'd suggest trying

`SELECT bbox FROM read_json_auto('https://earthquake.usgs.gov/earthquakes/feed/v1.0/summary/all_day.geojson');`

source: https://motherduck.com/blog/getting-started-gis-duckdb/

**Comment by Fil** [comment]
@fkauker-fsq exact same error

<img width="653" alt="Image" src="https://github.com/user-attachments/assets/d741995e-3b0f-4640-a01f-b862fbb60fdf" />

**Comment by carlopi** [comment]
Thanks for raising. I do reproduce.

Problem here is a non-trivial problem where the request being sent out of the browser has this headers:
```
Range	bytes=0-16383
Accept-Encoding	gzip, deflate, br, zstd, identity
```
and comes back a resource with those headers:
```
content-length	16384
content-encoding	gzip
```

Problem is that the resource here should have length 16384 AFTER decompression, while here it's 16384 pre-decompression and 125KB afterwards.

Given there is a browser in the middle, I would think here it's the server that it's not compliant, I would need to check how to detect this and fall back to a simpler strategy (ideally warning of current problem).

**Comment by greenmtnboy** [comment]
Any workarounds for this at the moment? Can you disable range requests?

**Comment by mootari** [comment]
@greenmtnboy Afaik the config options `allowFullHTTPReads` and `reliableHeadRequests` are meant to address that, but they may come with their own issues (see e.g. #1984).

**Comment by greenmtnboy** [comment]
Thanks! I played around with various combos of both and still got the same errors, but that might have been user error - I'll take another look. For now randomizing a URL suffix seems like the most reliable workaround.

**Comment by tobilg** [comment]
Is this eventually fixed by https://github.com/duckdb/duckdb-wasm/pull/2060?

**Comment by llimllib** [comment]
I reported this issue to github [here](https://github.com/orgs/community/discussions/178318) for whatever good that may do

**Comment by carlopi** [comment]
@llimllib:
Also, the 9th comment at https://bugzilla.mozilla.org/show_bug.cgi?id=1874840#c9 is relevant, where problem is more clearly identified, unsure if worth editing the issue to GitHub. Thanks for raising

**Comment by llimllib** [comment]
Thank you, I added a link in the issue text and saw your comment as well

**Comment by llimllib** [comment]
I also added a curl reproducer to the issue, which might help anybody investigating this:

```
# succeeds
$ curl 'https://llimllib.github.io/nba_data/gamelogs.parquet' -H 'Range: bytes=100-140' | xxd

# fails
$ curl 'https://llimllib.github.io/nba_data/gamelogs.parquet' --compressed -H 'Range: bytes=100-140' | xxd
```

If you want to see the raw gzip output, you can pass `accept-encoding` instead of `compressed`, which tells curl just to output the result instead of trying and failing to decompress it

```
$ curl 'https://llimllib.github.io/nba_data/gamelogs.parquet' \
    -H 'accept-encoding: deflate, gzip, br, zstd' \
    -H 'Range: bytes=100-140' | xxd
```

**Comment by llimllib** [comment]
It looks like this behavior [started sometime in July](https://github.com/protomaps/PMTiles/issues/584#issuecomment-3047685583)

That thread includes a terrible (but presumably functional) hack, which is to name your file ending in `.gz`, which will exclude it from the CDN's attempt to gzip the whole file and serve ranges of that copy

**Comment by bdon** [comment]
FYI this seems to have been fixed according to my test page: https://bdon.github.io/ghpages-firefox-range-bug/

**Comment by llimllib** [comment]
GitHub didn't fix their gzip encoding of ranged requests, but firefox added proper support for `Accept-Encoding: identity` that causes the request not to trigger GitHub's broken gzip ranged request handling
